blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name


urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('create', BlogCreateView.as_view(), name='create'),
    path('<int:pk>', BlogDetailView.as_view(), name='detail'),
    path('<int:pk>/update', BlogUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', BlogDeleteView.as_view(), name='delete'),




]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, ContactsTemplateView, ProductCreateView, \
    ProductUpdateView, ProductDeleteView, CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('category/', CategoryListView.as_view(), name='category_list'),
    path('product/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('product/create', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/update', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete', ProductDeleteView.as_view(), name='product_delete'),
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('catalog.urls', namespace='catalog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_confirm, reset_password, reset_password_success

app_name = UsersConfig.name

urlpatterns = [
    path('login', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('register/confirm/<str:token>', email_confirm, name='confirm'),
    path('register', UserCreateView.as_view(), name='register'),
    path('register/reset-password-success', reset_password_success, name='reset-password-success'),
    path('register/reset-password', reset_password, name='reset-password'),
]

catalog/models.py
from django.db import models

from config import NULLABLE
from users.models import User


class Category(models.Model):
    """ A class that implements the 'category' model. """

    title = models.CharField(max_length=128, verbose_name='категория')
    description = models.TextField( verbose_name='описание')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('id', )


class Product(models.Model):
    """ A class that implements the 'product' model. """

    title = models.CharField(max_length=128, verbose_name='продукт')
    description = models.TextField( verbose_name='описание')
    image = models.ImageField(upload_to='images/', **NULLABLE,  verbose_name='превью')
    category = models.ForeignKey(Category, on_delete=models.CASCADE,  verbose_name='категория')
    price = models.DecimalField(max_digits=10, decimal_places=2,  verbose_name='цена')
    created_at = models.DateTimeField(auto_now_add=True,  verbose_name='дата добавления')
    updated_at = models.DateTimeField(auto_now=True,  verbose_name='дата изменения')

    user = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='кто добавил', **NULLABLE)

    is_published = models.BooleanField(default=False, verbose_name='опубликовано')

    def __str__(self):
        return f'{self.title}, цена: {self.price}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('id', )
        permissions = [
            ('set_published', 'Can publish product'),
            ('set_category', 'Can change category'),
            ('set_description', 'Can change description'),
        ]


class Version(models.Model):
    """ A class that implements the 'version' model. """

    product = models.ForeignKey(Product, on_delete=models.CASCADE,  verbose_name='продукт')
    number = models.CharField(max_length=32, verbose_name='номер версии')
    title = models.CharField(max_length=128, verbose_name='название версии')
    is_current = models.BooleanField(default=False, verbose_name='текущая')
    created_at = models.DateTimeField(auto_now_add=True,  verbose_name='дата добавления')
    updated_at = models.DateTimeField(auto_now=True,  verbose_name='дата изменения')

    def __str__(self):
        return f'{self.number}: {self.title}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'
        ordering = ('product', 'is_current', 'number', )

catalog/forms.py
from django import forms

from catalog.funcs import check_banned_words
from catalog.models import Product, Version


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ("title", "description", "image", "category", "price", )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if not isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-control'

    def clean_title(self):
        cleaned_data = self.cleaned_data.get('title')
        banned_word = check_banned_words(cleaned_data)
        if banned_word:
            raise forms.ValidationError(f'Отказано. В названии продукта содержится запрещенное слово: {banned_word}.')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description')
        banned_word = check_banned_words(cleaned_data)
        if banned_word:
            raise forms.ValidationError(f'Отказано. В описании продукта содержится запрещенное слово: {banned_word}.')
        return cleaned_data


class ProductModeratorForm(ProductForm):

    class Meta:
        model = Product
        fields = ("description", "category", "is_published", )


class VersionForm(forms.ModelForm):

    class Meta:
        model = Version
        fields = ("product", "number", "title", "is_current", )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if isinstance(field, forms.fields.BooleanField):
                field.widget.attrs['class'] += ' form-check-input'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView

from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Version, Category
from catalog.services import get_category_list, get_product_list


class ProductListView(ListView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        for obj in context_data['object_list']:
            current_version = Version.objects.filter(product_id=obj.pk, is_current=True).first()
            obj.version = current_version
        return context_data

    def get_queryset(self):
        return get_product_list()


class ProductDetailView(DetailView):
    model = Product


class ContactsTemplateView(TemplateView):
    template_name = "catalog/contacts.html"

    def post(self, request, *args, **kwargs):
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        message = request.POST.get("message")
        print(f"name: {name}, email: {phone}, message: {message}")
        return self.get(request, *args, **kwargs)


class ProductCreateView(LoginRequiredMixin, CreateView):
    login_url = "/users/login"

    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def form_valid(self, form):
        product = form.save()
        product.user = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    login_url = "/users/login"

    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()["formset"]
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user
        if user == self.object.user:
            return ProductForm
        elif user.has_perm('catalog.set_published') and \
                user.has_perm('catalog.set_category') and \
                user.has_perm('catalog.set_description'):
            return ProductModeratorForm
        else:
            raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    login_url = "/users/login"

    model = Product
    success_url = reverse_lazy('catalog:product_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.user:
            return self.object
        raise PermissionDenied


class CategoryListView(ListView):
    model = Category

    def get_queryset(self):
        return get_category_list()

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
{% include 'catalog/main_menu.html' %}

{% block banner %}{% endblock %}

<div class="container">
    {% block content %}{% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h3 class="display-6">Список доступных категорий</h3>
</div>

<div class="container">
    <div class="row">
        <div class="text-center">
            <ul class="list-group">
                {% for object in object_list %}
                <li class="list-group-item list-group-item-action list-group-item-info mb-3">{{ object.title }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}
{% block banner %}{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea name="message" class="form-control" id="message" placeholder="Введите сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block banner %}{% endblock %}

catalog/templates/catalog/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Удобный сервис рассылок</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ 140</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Неограниченная лицензия</li>
                        <li>- Поддержка</li>
                        <li>- Установка на сервер</li>
                        <li>- Получение обновлений</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/main.html
{% extends 'catalog/base.html' %}
{% load media %}
{% block content %}
    <div class="row text-center">
        {% for object in objects %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                    <h6>{{ object.category.title }}</h6>
                </div>
                <div class="card-body">
                    {% if object.image %}
                    <img src="{% url_media_tag object.image %}" width="100%" />
                    {% endif %}
                    <h1 class="card-title pricing-card-title">{{ object.price }} руб.</h1>
                    <p>{{ object.description|slice:100 }}</p>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Создан: {{ object.created_at }}</li>
                        <li>Изменён: {{ object.updated_at }}</li>
                    </ul>
                    <a href="{% url 'catalog:product_detail' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Просмотр</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/main_menu.html
{% block main_menu %}

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:category_list' %}">Категории</a>
        <a class="p-2 btn btn-outline-primary" href="/blog">Блоги</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
        {% endif %}
    </nav>
</div>

{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<h4>Удалить продукт {{ object.title }}?</h4>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'catalog:product_list' %}" class="btn btn-warning">Отмена</a>
</form>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load media %}
{% block content %}
<div class="row text-center">
    <div class="col-8 offset-2">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                <h6>{{ object.category.title }}</h6>
            </div>
            <div class="card-body">
                {% if object.image %}
                <img src="{{ object.image|url_media_filter }}" width="100%" />
                {% endif %}
                <h1 class="card-title pricing-card-title">{{ object.price }} руб.</h1>
                <p>{{ object.description }}</p>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>Создан: {{ object.created_at }}</li>
                    <li>Изменён: {{ object.updated_at }}</li>
                </ul>
                <a href="{% url 'catalog:product_list' %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Закрыть</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block banner %}{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}


<form method="post" enctype="multipart/form-data">
    <div class="row">
        {% csrf_token %}
        <div class="col-6">
            {% if object %}
            <h4>Редактирование продукта</h4>
            {% else %}
            <h4>Добавление продукта</h4>
            {% endif %}
            {{ form.as_p }}
        </div>
        <div class="col-6">
            {% if object and user == object.user %}
            <h4>Версии</h4>
            {{ formset.management_form }}
            {% for form in formset.forms %}
            {{ form.as_p }}
            {% if not forloop.last %}
            <hr>
            {% endif %}
            {% endfor %}
            {% endif %}
        </div>

    </div>
    <div class="row">
        <div class="col-12">
            {% if object %}
            <button type="submit" class="btn btn-primary">Сохранить</button>
            {% else %}
            <button type="submit" class="btn btn-success">Добавить</button>
            {% endif %}
            <a href="{% url 'catalog:product_list' %}" class="btn btn-danger">Отмена</a>
        </div>
    </div>
</form>

{% endblock %}
{% block banner %}{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load media %}
{% block content %}
    <div class="row text-center">
        {% if user.is_authenticated %}
        <a class="btn btn-primary mb-5" href="{% url 'catalog:product_create' %}">Добавить продукт</a>
        {% endif %}
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                    <h6>{{ object.category.title }}</h6>
                </div>
                <div class="card-body">
                    {% if object.image %}
                    <img src="{% url_media_tag object.image %}" width="100%" />
                    {% endif %}
                    <h1 class="card-title pricing-card-title">{{ object.price }} руб.</h1>
                    <p>{{ object.description|slice:100 }}</p>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Создан: {{ object.created_at }}</li>
                        <li>Изменён: {{ object.updated_at }}</li>
                        {% if object.version %}
                        <li>Версия: <strong>{{ object.version.number }}</strong> {{ object.version.title }}</li>
                        {% endif %}
                    </ul>
                    <a href="{% url 'catalog:product_detail' object.pk %}" type="button" class="btn btn-primary w-100 mb-1">Просмотр</a>
                    {% if user == object.user %}
                    <a href="{% url 'catalog:product_update' object.pk %}" type="button" class="btn btn-warning w-100 mb-1">Редактировать</a>
                    <a href="{% url 'catalog:product_delete' object.pk %}" type="button" class="btn btn-danger w-100 mb-1">Удалить</a>
                    {% endif %}
                    {% if perms.catalog.set_published %}
                    <a href="{% url 'catalog:product_update' object.pk %}" type="button" class="btn btn-warning w-100 mb-1">Модерировать</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

{% block banner %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>
{% endblock %}